client_id = "4ef1ce49f9f58d050c762000e78ecf71"
name = "Search"
application_url = "https://search-0wf4.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
scopes = "read_products,read_inventory"

[auth]
redirect_urls = [ "https://search-0wf4.onrender.com/auth/callback" ]