api_version = "2025-04"

[[extensions]]

uid = "e893bca6-9ab4-6a83-745e-a1347013f84d882acb9d"

type = "ui_extension"
name = "Search"
handle = "search"

[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"

[extensions.capabilities]
network_access = true